### ISSUE TITLE
Why last layer dont use any activation?

### ISSUE THREAD

**Issue by rodrigo2019** [pskrunner14/trading-bot#2]
Hello, first of all, thanks for sharing.

I was looking your model and I saw something strange. Why are you not using any activation in the last layer?
This problem looks like a classification problem, the bot can choose just one option (sit, buy or sell), so using softmax activation should be better? What do you think?

**Comment by pskrunner14** [comment]
Hi @rodrigo2019 thanks for your interest.
Traditionally yes you'd be right that something like softmax would be necessary in a classification problem, but in the context of Q-learning, the network acts as a Q-function that approximates q-values which are essentially expected reward (quality of an action) given the current state, so inherently it turns into a regression problem. Choosing the optimal action is basically an argmax operation on the q-values.
You can refer to the DQN paper for more intuition on this.

**Comment by rodrigo2019** [comment]
Thank you @pskrunner14 , your explanation was very clear
